using AutoFixture;
using AutoFixture.AutoMoq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Moq;
using WebMessenger.Api.Controllers;
using WebMessenger.Api.Hubs.Events.Interfaces;
using WebMessenger.Api.Infrastructure.Interfaces;
using WebMessenger.Api.Services.Interfaces;
using WebMessenger.Api.Tests.Shared.TestData;
using WebMessenger.Contracts.Models;

namespace WebMessenger.Api.Tests.Unit.Controllers;

/// <summary>
/// AutoFixture + AutoMoq demonstration using ChatController.
///
/// KEY AutoFixture CONCEPTS:
/// ─────────────────────────────────────────────────────────────────────
/// 1. fixture.Create&lt;T&gt;()
///    Generates an instance of T with all properties filled with random
///    but type-safe values. Eliminates manual new Dto { ... } boilerplate.
///
/// 2. fixture.CreateMany&lt;T&gt;(count)
///    Generates a collection of count instances of T.
///
/// 3. fixture.Build&lt;T&gt;().With(x =&gt; x.Prop, value).Create()
///    Generates an object but explicitly pins specific properties;
///    the rest are filled automatically.
///
/// 4. fixture.Freeze&lt;T&gt;()
///    "Freezes" an instance — subsequent Create() calls return the same
///    object. Critical for mocks: ensures the SUT and the test share the
///    exact same Mock&lt;T&gt; instance.
///
/// 5. fixture.Create&lt;SUT&gt;() with AutoMoqCustomization
///    AutoMoq automatically creates mocks for all interface constructor
///    parameters and injects them. No need to manually list new Mock&lt;IService&gt;().
/// ─────────────────────────────────────────────────────────────────────
/// </summary>
public class ChatControllerAutoFixtureTests
{
    private readonly IFixture _fixture;
    private readonly Mock<IChatService> _chatServiceMock;
    private readonly Mock<IChatEvents> _chatEventsMock;
    private readonly Mock<ICurrentUser> _currentUserMock;
    private readonly ChatController _sut;
    private readonly Guid _userId;

    public ChatControllerAutoFixtureTests()
    {
        // ── Step 1: create the fixture with AutoMoq ──────────────────────────
        // FixtureFactory.Create() internally does:
        //   var fixture = new Fixture();
        //   fixture.Customize(new AutoMoqCustomization { ConfigureMembers = true });
        // ConfigureMembers = true means AutoMoq will configure not just the
        // interfaces themselves but also all their methods and properties.
        _fixture = FixtureFactory.Create();

        // ── Step 2: Freeze — pin the mock instance ──────────────────────────
        // Freeze guarantees that when the fixture resolves ChatController
        // it will use exactly this mock instance — the one we hold in the field.
        // Without Freeze each Create() would return a NEW Mock, so our Setup
        // would be on a different object than the one injected into the controller.
        _chatServiceMock  = _fixture.Freeze<Mock<IChatService>>();
        _chatEventsMock   = _fixture.Freeze<Mock<IChatEvents>>();
        _currentUserMock  = _fixture.Freeze<Mock<ICurrentUser>>();

        // ── Step 3: fix the userId and configure ICurrentUser ─────────────────
        _userId = Guid.NewGuid();
        _currentUserMock.Setup(u => u.Id).Returns(_userId);

        // ── Step 4: construct the controller manually from the frozen mocks ────
        // IMPORTANT: for ASP.NET Core controllers do NOT use fixture.Create<T>(),
        // because AutoFixture will try to populate ControllerContext →
        // ControllerActionDescriptor → BindingInfo — an internal MVC field that
        // has special validation and throws an exception when set via reflection.
        //
        // Correct pattern: resolve dependencies via Freeze (AutoMoq),
        // then create the controller with new() manually.
        // ILogger<ChatController> is also resolved through the fixture — AutoMoq mocks it.
        var logger = _fixture.Create<ILogger<ChatController>>();
        _sut = new ChatController(
            _currentUserMock.Object,
            _chatServiceMock.Object,
            logger,
            _chatEventsMock.Object);
        _sut.ControllerContext = new ControllerContext { HttpContext = new DefaultHttpContext() };
    }

    // =========================================================================
    // CONCEPT: fixture.Create<T>() for DTO generation
    // =========================================================================

    [Fact]
    public async Task Index_ReturnsOk_WithAutoGeneratedPagedResult()
    {
        // Arrange ─────────────────────────────────────────────────────────────
        // fixture.Create<PagedResult<ChatListItemDto>>() automatically:
        //  - creates a PagedResult
        //  - fills Items with several auto-generated ChatListItemDto instances
        //  - sets HasMore to a random bool, NextBefore to a random DateTime?
        // No need to write new PagedResult<> { Items = new List<> { new() {...} } }
        var fakeResult = _fixture.Create<PagedResult<ChatListItemDto>>();
        _chatServiceMock
            .Setup(s => s.GetUserChatsAsync(_userId, 20, null))
            .ReturnsAsync(fakeResult);

        // Act
        var result = await _sut.Index(limit: 20);

        // Assert
        var ok = Assert.IsType<OkObjectResult>(result.Result);
        Assert.Equal(fakeResult, ok.Value);
    }

    // =========================================================================
    // CONCEPT: fixture.Create<Guid>() and Create<T>() for parameters
    // =========================================================================

    [Fact]
    public async Task GetChatHeader_ExistingChat_ReturnsOkWithHeader()
    {
        // Arrange ─────────────────────────────────────────────────────────────
        // fixture.Create<Guid>() — random but valid Guid
        var chatId = _fixture.Create<Guid>();

        // fixture.Create<DirectChatHeaderDto>() — the entire DTO is filled automatically
        var header = _fixture.Create<DirectChatHeaderDto>();

        _chatServiceMock
            .Setup(s => s.GetChatHeaderByChatIdAsync(_userId, chatId))
            .ReturnsAsync(header);

        // Act
        var result = await _sut.GetChatHeader(chatId);

        // Assert
        var ok = Assert.IsType<OkObjectResult>(result);
        Assert.Equal(header, ok.Value);
    }

    [Fact]
    public async Task GetChatHeader_ChatNotFound_ReturnsNotFound()
    {
        // Arrange
        var chatId = _fixture.Create<Guid>();
        _chatServiceMock
            .Setup(s => s.GetChatHeaderByChatIdAsync(_userId, chatId))
            .ReturnsAsync((DirectChatHeaderDto?)null);

        // Act
        var result = await _sut.GetChatHeader(chatId);

        // Assert
        Assert.IsType<NotFoundResult>(result);
    }

    // =========================================================================
    // CONCEPT: fixture.CreateMany<T>() for collections
    // =========================================================================

    [Fact]
    public async Task GetMessages_ReturnsPaged_WithAutoGeneratedMessages()
    {
        // Arrange ─────────────────────────────────────────────────────────────
        var chatId = _fixture.Create<Guid>();

        // CreateMany<T>(3) — a list of 3 fully populated objects;
        // each ChatMessageDto gets a unique Id, random Content, SentAt, etc.
        var messages = _fixture.CreateMany<ChatMessageDto>(3).ToList();
        var pagedResult = new PagedResult<ChatMessageDto>
        {
            Items = messages,
            HasMore = false
        };

        _chatServiceMock
            .Setup(s => s.GetMessagesAsync(_userId, chatId, 50, null))
            .ReturnsAsync(pagedResult);

        // Act
        var result = await _sut.GetMessages(chatId, limit: 50);

        // Assert
        var ok = Assert.IsType<OkObjectResult>(result.Result);
        var returned = Assert.IsAssignableFrom<PagedResult<ChatMessageDto>>(ok.Value);
        Assert.Equal(3, returned.Items.Count);
    }

    // =========================================================================
    // CONCEPT: fixture.Build<T>().With(...).Create() — partial customization
    // =========================================================================

    [Fact]
    public async Task SendMessage_ValidContent_ReturnsOkAndFiresEvent()
    {
        // Arrange ─────────────────────────────────────────────────────────────
        var targetUserId = _fixture.Create<Guid>();

        // Build<T>().With(...).Create() — generate a request but FIX the Content.
        // Everything else (if there were more fields) would be filled by AutoFixture.
        // Useful when you need to assert on a specific field value
        // while the rest are irrelevant.
        var request = _fixture.Build<SendMessageRequest>()
            .With(r => r.Content, "Hello from AutoFixture!")
            .Create();

        // fixture.Create<SendMessageResponse>() — the entire response is filled automatically
        var response = _fixture.Create<SendMessageResponse>();

        _chatServiceMock
            .Setup(s => s.SendMessageToUserAsync(_userId, targetUserId, request.Content, It.IsAny<CancellationToken>()))
            .ReturnsAsync(response);

        // Act
        var result = await _sut.SendMessage(targetUserId, request, CancellationToken.None);

        // Assert
        var ok = Assert.IsType<OkObjectResult>(result.Result);
        Assert.Equal(response, ok.Value);

        // Verify: the service method was called exactly once with the expected content
        _chatServiceMock.Verify(
            s => s.SendMessageToUserAsync(_userId, targetUserId, "Hello from AutoFixture!", It.IsAny<CancellationToken>()),
            Times.Once);
    }

    // =========================================================================
    // CONCEPT: Freeze + Verify for cross-service interaction assertions
    // =========================================================================

    [Fact]
    public async Task MarkRead_CallsReadReceiptEvent_AfterMarkingRead()
    {
        // Arrange ─────────────────────────────────────────────────────────────
        var chatId    = _fixture.Create<Guid>();
        var readState = _fixture.Create<ReadStateDto>();

        _chatServiceMock
            .Setup(s => s.MarkChatReadAsync(_userId, chatId, null))
            .ReturnsAsync(readState);

        // IChatEvents was also frozen — so the Verify below operates on
        // the exact same instance that was injected into the controller
        _chatEventsMock
            .Setup(e => e.ReadReceiptAsync(chatId, _userId, readState.LastReadAt, It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);

        // Act — null body means: mark as read up to the current moment
        var result = await _sut.MarkRead(chatId, body: null, CancellationToken.None);

        // Assert
        Assert.IsType<OkObjectResult>(result);

        // Verify that the SignalR ReadReceiptAsync event was actually fired
        _chatEventsMock.Verify(
            e => e.ReadReceiptAsync(chatId, _userId, readState.LastReadAt, It.IsAny<CancellationToken>()),
            Times.Once);
    }

    [Fact]
    public async Task GetReadState_ReturnsOkWithState()
    {
        // Arrange
        var chatId    = _fixture.Create<Guid>();
        var readState = _fixture.Create<ReadStateDto>();

        _chatServiceMock
            .Setup(s => s.GetReadStateAsync(_userId, chatId))
            .ReturnsAsync(readState);

        // Act
        var result = await _sut.GetReadState(chatId);

        // Assert
        Assert.IsType<OkObjectResult>(result);
    }
}
